/** Narration localisée du moteur de jeu.
 *
 *  Le moteur (`src/game/engine.ts`) ne stocke plus de phrases françaises :
 *  il émet des jetons `⟦clé⟧{"var":"valeur"}` créés par `nk()`.
 *  L'interface les rend dans la langue active via `resolveNarration()`.
 *
 *  Les valeurs de variables peuvent elles-mêmes être des jetons (imbrication),
 *  ce qui permet de traduire une cause de mort ou un nom de rôle à l'intérieur
 *  d'une phrase.
 */

import type { Lang } from "@/lib/i18n";
import { ROLE_BY_ID } from "@/data/roles";
import { fr as frDict } from "@/lib/locales/fr";
import { en as enDict } from "@/lib/locales/en";
import { ar as arDict } from "@/lib/locales/ar";
import { es as esDict } from "@/lib/locales/es";
import { pt as ptDict } from "@/lib/locales/pt";
import { ru as ruDict } from "@/lib/locales/ru";
import { zh as zhDict } from "@/lib/locales/zh";
import { nl as nlDict } from "@/lib/locales/nl";
import { de as deDict } from "@/lib/locales/de";

const OPEN = "\u27E6";
const CLOSE = "\u27E7";

/** Construit un jeton de narration traduisible. */
export function nk(key: string, vars: Record<string, string | number> = {}): string {
  return `${OPEN}${key}${CLOSE}${JSON.stringify(vars)}`;
}

/** Jeton spécial : nom de rôle traduit. */
export function nrole(roleId: string): string {
  return nk("@role", { id: roleId });
}

type Table = Record<string, string>;

const NARRATION: Partial<Record<Lang, Table>> & { fr: Table } = {
  fr: {
    logVoteTally: "Jour {d} — Vote : [{tally}] → Éliminé(s) : {names}",
    lovers: "{a} et {b} sont désormais amoureux.",
    logCupid: "Cupidon lie {a} et {b}.",
    mimeCopy: "Tu copies le rôle : {role}.",
    wildModel: "Ton modèle est {name}.",
    jailExecuted: "{name} est exécuté dans sa geôle.",
    jailLocked: "{name} passe la nuit sous les verrous, à l'abri des crocs.",
    seerSees: "{name} est : {role}.",
    shieldUltimate: "Le Bouclier Ultime enveloppe le village entier — le Salvateur perd ses pouvoirs.",
    logShieldUltimate: "Nuit {n} : Bouclier Ultime activé par {name}.",
    protectedTonight: "{name} est protégé cette nuit.",
    spyCaught: "Tu as été repérée par la meute… tu ne verras pas l'aube.",
    spyHint: "Tu aperçois une silhouette : l'initiale « {letter} ».",
    spyNothing: "Tu n'aperçois rien dans l'obscurité.",
    eyesClosed: "Tu gardes les yeux fermés.",
    packDisagree: "Désaccord dans la meute : les loups se rendorment, la Matriarche va trancher.",
    packChose: "La meute a choisi {name}.",
    matriarchImpose: "La Matriarche impose {name}.",
    logMatriarch: "La Matriarche tranche : {name}.",
    logSoloKill: "{role} dévore {name} (meute solitaire).",
    talkativeWord: "Mot imposé au Loup Bavard : « {word} ». Il devra le prononcer pendant le débat.",
    infectBlocked: "La contamination échoue : la cible est protégée.",
    logInfectBlocked: "Contamination bloquée par le Salvateur — pouvoir conservé.",
    infectJoin: "{name} rejoint la meute en gardant son pouvoir.",
    logInfect: "Le Loup Noir contamine {name}.",
    silenceNote: "{name} ne pourra pas débattre demain matin.",
    logSilence: "Le Loup Noir impose le silence à {name}.",
    packAsPlanned: "La meute dévore comme prévu.",
    whiteTarget: "{name} sera dévoré par le Loup Blanc.",
    witchSaved: "La victime des loups est sauvée.",
    poisoned: "{name} est empoisonné.",
    fluteCharm: "La mélodie envoûte deux nouvelles âmes.",
    ravenVotes: "{name} commencera le vote avec 2 voix.",
    tavernDrink: "{name} a bu : demain il ne pourra pas voter, mais sera intouchable.",
    bearGrowl: "🐻 L'Ours grogne.",
    bearCalm: "Tout va bien.",
    generalWolf: "{name} était un Loup : il est abattu. {actor} devient le nouveau Capitaine.",
    logGeneralWolf: "Le Général abat {name} et devient Capitaine.",
    generalFail: "{name} n'était pas un Loup : le Général est éliminé par le Maître du Jeu.",
    logGeneralFail: "Le coup du Général échoue sur {name}.",
    generalIdle: "Le Général n'agit pas cette nuit.",
    survivedAttack: "{name} a survécu à l'attaque… pour cette fois.",
    deathLine: "{name} est mort — {cause}.",
    logDeath: "{name} ({role}) — {cause}.",
    elderFall: "L'Ancien est tombé par la main du village : tous les villageois perdent leurs pouvoirs.",
    wildAwaken: "{name} sent la bête s'éveiller en lui…",
    redRidingHood: "Le Chaperon Rouge est resté sous la garde du Chasseur : l'attaque échoue.",
    villageShieldSaved: "🛡️ Le Bouclier Ultime a protégé le village entier cette nuit.",
    saviorFoiled: "Le Salvateur a déjoué l'attaque des loups.",
    jailerSafe: "Le prisonnier du Geôlier était hors d'atteinte.",
    bearNear: "🐻 L'ours grogne : un loup est tout près !",
    mutedToday: "{name} est muet : il ne peut pas débattre aujourd'hui.",
    nobodyDied: "Étrangement, personne n'est mort cette nuit.",
    newCaptain: "{name} devient le nouveau Capitaine.",
    day1NoVote: "Jour 1 : le village a refusé de voter.",
    logTalkativeExecuted: "Jour {d} — Loup Bavard exécuté (mot non prononcé) ; vote annulé.",
    nightHeader: "— Nuit {n} —",
    killerFallback: "Nuit {n} : aucun loup standard — la mise à mort revient au {role}.",
    idiotSurvives: "{name} est l'Idiot du Village : il survit mais perd son droit de vote.",
    untouchableToday: "{name} était intouchable aujourd'hui.",
    winAngel: "{name} — l'Ange gagne : le village l'a exécuté au premier jour.",
    winNobody: "Personne ne survit. Le village est éteint.",
    winLovers: "Les Amoureux gagnent : {a} & {b}.",
    winWhiteWolf: "Le Loup Blanc {name} reste seul : victoire solitaire.",
    winPiper: "Le Joueur de Flûte {name} a envoûté le village entier.",
    winVillage: "Le Village triomphe : plus aucun loup ne rôde.",
    winWolves: "Les Loups-Garous ont dévoré le village.",
    thiefSteal: "Tu voles le rôle de {name} : {role}. {name} devient Simple Villageois.",
    logThiefSteal: "Le Voleur vole le rôle de {name} ({role}).",
    facesProtectMsg: "3 faces protège {name} cette nuit.",
    facesInspectMsg: "3 faces découvre : {name} est {role}.",
    facesLifeMsg: "3 faces utilise la potion de vie : la victime des loups est sauvée.",
    facesPoisonMsg: "3 faces empoisonne {name}.",
    logFaces: "3 faces utilise le visage « {power} » sur {name}.",
    maniacTargetMsg: "Le Maniaque frappe {name} — aucune protection ne l'arrête.",
    logManiac: "Le Maniaque assassine {name}.",
    winManiac: "Le Maniaque {name} reste maître du village : victoire solitaire.",
    repWolvesTarget: "🐺 Meute des Loups → {name}",
    repNoWolvesTarget: "🐺 Meute des Loups → aucune victime",
    repManiacTarget: "🔪 Maniaque → {name} (attaque imparable)",
    repSeerCheck: "🔮 {role} inspecte {name} → {result}",
    repProtect: "🛡️ {role} protège {name}",
    repVillageShield: "🛡️ Bouclier Ultime : village entier protégé",
    repWitchLife: "⚗️ Potion de vie utilisée sur {name}",
    repWitchPoison: "☠️ Potion de mort utilisée sur {name}",
    repSilence: "🤐 Loup Noir impose le silence à {name}",
    repSilenceSelf: "🤐 Loup Noir s'impose le silence à lui-même ({name})",
    repInfect: "🩸 Loup Noir contamine {name}",
    repThief: "🎭 Le Voleur ({thief}) vole le rôle de {name} → {role} ; {name} devient Simple Villageois",
    repFaces: "🎭 3 faces utilise « {power} » sur {name}",
    repDied: "💀 {name} ({role}) — {cause}",
    repSavedBy: "✨ {name} sauvé par {role}",
    repMuted: "🤐 {name} ne pourra pas débattre aujourd'hui",
    repNoDeaths: "Aucune mort cette nuit.",
    repFacePower_protect: "Protection",
    repFacePower_life: "Potion de vie",
    repFacePower_poison: "Potion de mort",
    repFacePower_inspect: "Inspection",
    cause_MANIAC: "assassiné par le Maniaque",
    cause_SUICIDE_REVEAL: "Suicide / Révélation de rôle",
    logSuicideReveal: "{name} a révélé son identité : suicide immédiat.",
    cause_THREE_FACES_POISON: "empoisonné par 3 faces",
    cause_WOLVES: "dévoré par les loups",
    cause_WITCH_POISON: "empoisonné par la Sorcière",
    cause_WHITE_WOLF_KILL: "égorgé par le Loup Blanc",
    cause_HUNTER_SHOT: "abattu par le Chasseur",
    cause_HEARTBREAK: "mort de chagrin",
    cause_VILLAGE_VOTE: "exécuté par le village",
    cause_JAILER_EXECUTION: "exécuté par le Geôlier",
    cause_SPY_DETECTED: "repérée par la meute",
    cause_TALKATIVE_WOLF: "trahi par son silence",
    cause_GENERAL_STRIKE: "abattu par le Général",
    cause_GENERAL_FAILED: "éliminé par le Maître du Jeu (coup manqué du Général)",
    puppetSaved: "{name} a été attaqué(e), mais son pantin a absorbé le coup ! Il/Elle survit, mais est réduit(e) au silence pour le débat du jour.",
    repPuppetSaved: "🎭 {name} (Marionnettiste) a absorbé l'attaque grâce à son pantin et est réduit(e) au silence.",
  },
  en: {
    logVoteTally: "Day {d} — Vote: [{tally}] → Eliminated: {names}",
    lovers: "{a} and {b} are now lovers.",
    logCupid: "Cupid binds {a} and {b}.",
    mimeCopy: "You copy the role: {role}.",
    wildModel: "Your model is {name}.",
    jailExecuted: "{name} is executed in the cell.",
    jailLocked: "{name} spends the night locked up, safe from the fangs.",
    seerSees: "{name} is: {role}.",
    shieldUltimate: "The Ultimate Shield wraps the whole village — the Savior loses their powers.",
    logShieldUltimate: "Night {n}: Ultimate Shield activated by {name}.",
    protectedTonight: "{name} is protected tonight.",
    spyCaught: "The pack spotted you… you will not see the dawn.",
    spyHint: "You glimpse a silhouette: initial “{letter}”.",
    spyNothing: "You see nothing in the darkness.",
    eyesClosed: "You keep your eyes shut.",
    packDisagree: "The pack disagrees: the wolves fall back asleep, the Matriarch will decide.",
    packChose: "The pack chose {name}.",
    matriarchImpose: "The Matriarch imposes {name}.",
    logMatriarch: "The Matriarch decides: {name}.",
    logSoloKill: "{role} devours {name} (lone pack).",
    talkativeWord: "Secret word for the Talkative Wolf: “{word}”. He must say it during the debate.",
    infectBlocked: "The infection fails: the target is protected.",
    logInfectBlocked: "Infection blocked by the Savior — power retained.",
    infectJoin: "{name} joins the pack and keeps their power.",
    logInfect: "The Black Wolf infects {name}.",
    silenceNote: "{name} will not be able to debate tomorrow morning.",
    logSilence: "The Black Wolf silences {name}.",
    packAsPlanned: "The pack devours as planned.",
    whiteTarget: "{name} will be devoured by the White Wolf.",
    witchSaved: "The wolves' victim is saved.",
    poisoned: "{name} is poisoned.",
    fluteCharm: "The melody charms two more souls.",
    ravenVotes: "{name} starts the vote with 2 votes.",
    tavernDrink: "{name} drank: tomorrow they cannot vote, but they are untouchable.",
    bearGrowl: "🐻 The Bear growls.",
    bearCalm: "All is well.",
    generalWolf: "{name} was a Wolf: shot down. {actor} becomes the new Captain.",
    logGeneralWolf: "The General shoots {name} and becomes Captain.",
    generalFail: "{name} was not a Wolf: the General is removed by the Game Master.",
    logGeneralFail: "The General's shot fails on {name}.",
    generalIdle: "The General does not act tonight.",
    survivedAttack: "{name} survived the attack… this time.",
    deathLine: "{name} is dead — {cause}.",
    logDeath: "{name} ({role}) — {cause}.",
    elderFall: "The Elder fell by the village's hand: every villager loses their powers.",
    wildAwaken: "{name} feels the beast awaken within…",
    redRidingHood: "Little Red Riding Hood stayed under the Hunter's guard: the attack fails.",
    villageShieldSaved: "🛡️ The Ultimate Shield protected the whole village tonight.",
    saviorFoiled: "The Savior thwarted the wolves' attack.",
    jailerSafe: "The Jailer's prisoner was out of reach.",
    bearNear: "🐻 The bear growls: a wolf is very close!",
    mutedToday: "{name} is silenced: they cannot debate today.",
    nobodyDied: "Strangely, nobody died tonight.",
    newCaptain: "{name} becomes the new Captain.",
    day1NoVote: "Day 1: the village refused to vote.",
    logTalkativeExecuted: "Day {d} — Talkative Wolf executed (word not said); vote cancelled.",
    nightHeader: "— Night {n} —",
    killerFallback: "Night {n}: no standard wolf — the kill falls to the {role}.",
    idiotSurvives: "{name} is the Village Idiot: they survive but lose the right to vote.",
    untouchableToday: "{name} was untouchable today.",
    winAngel: "{name} — the Angel wins: the village executed them on the first day.",
    winNobody: "Nobody survives. The village is extinguished.",
    winLovers: "The Lovers win: {a} & {b}.",
    winWhiteWolf: "The White Wolf {name} stands alone: solitary victory.",
    winPiper: "The Pied Piper {name} charmed the entire village.",
    winVillage: "The Village triumphs: no wolf prowls anymore.",
    winWolves: "The Werewolves have devoured the village.",
    thiefSteal: "You steal {name}'s role: {role}. {name} becomes a plain Villager.",
    logThiefSteal: "The Thief steals {name}'s role ({role}).",
    facesProtectMsg: "3 faces protects {name} tonight.",
    facesInspectMsg: "3 faces discovers: {name} is {role}.",
    facesLifeMsg: "3 faces uses the life potion: the wolves' victim is saved.",
    facesPoisonMsg: "3 faces poisons {name}.",
    logFaces: "3 faces uses the “{power}” face on {name}.",
    maniacTargetMsg: "The Maniac strikes {name} — no protection can stop it.",
    logManiac: "The Maniac murders {name}.",
    winManiac: "The Maniac {name} rules what is left of the village: solitary victory.",
    repWolvesTarget: "🐺 Werewolf pack → {name}",
    repNoWolvesTarget: "🐺 Werewolf pack → no victim",
    repManiacTarget: "🔪 Maniac → {name} (unstoppable attack)",
    repSeerCheck: "🔮 {role} inspects {name} → {result}",
    repProtect: "🛡️ {role} protects {name}",
    repVillageShield: "🛡️ Ultimate Shield: whole village protected",
    repWitchLife: "⚗️ Life potion used on {name}",
    repWitchPoison: "☠️ Poison potion used on {name}",
    repSilence: "🤐 Black Wolf silences {name}",
    repSilenceSelf: "🤐 Black Wolf silences himself ({name})",
    repInfect: "🩸 Black Wolf infects {name}",
    repThief: "🎭 The Thief ({thief}) steals {name}'s role → {role}; {name} becomes a plain Villager",
    repFaces: "🎭 3 faces uses “{power}” on {name}",
    repDied: "💀 {name} ({role}) — {cause}",
    repSavedBy: "✨ {name} saved by {role}",
    repMuted: "🤐 {name} cannot debate today",
    repNoDeaths: "Nobody died tonight.",
    repFacePower_protect: "Protection",
    repFacePower_life: "Life potion",
    repFacePower_poison: "Poison potion",
    repFacePower_inspect: "Inspection",
    cause_MANIAC: "murdered by the Maniac",
    cause_SUICIDE_REVEAL: "Suicide / role reveal",
    logSuicideReveal: "{name} revealed their identity: immediate suicide.",
    cause_THREE_FACES_POISON: "poisoned by 3 faces",
    cause_WOLVES: "devoured by the wolves",
    cause_WITCH_POISON: "poisoned by the Witch",
    cause_WHITE_WOLF_KILL: "slain by the White Wolf",
    cause_HUNTER_SHOT: "shot by the Hunter",
    cause_HEARTBREAK: "died of heartbreak",
    cause_VILLAGE_VOTE: "executed by the village",
    cause_JAILER_EXECUTION: "executed by the Jailer",
    cause_SPY_DETECTED: "spotted by the pack",
    cause_TALKATIVE_WOLF: "betrayed by their silence",
    cause_GENERAL_STRIKE: "shot by the General",
    cause_GENERAL_FAILED: "removed by the Game Master (the General missed)",
    puppetSaved: "{name} was attacked, but their puppet absorbed the strike! They survive, but are silenced for today's debate.",
    repPuppetSaved: "🎭 {name} (Puppeteer) absorbed the attack using their puppet and is silenced.",
  },
  ar: {
    logVoteTally: "اليوم {d} — التصويت: [{tally}] ← المُقصى: {names}",
    lovers: "{a} و {b} أصبحا عاشقين.",
    logCupid: "كيوبيد يربط {a} و {b}.",
    mimeCopy: "أنت تنسخ الدور: {role}.",
    wildModel: "قدوتك هي {name}.",
    jailExecuted: "تم إعدام {name} في زنزانته.",
    jailLocked: "يقضي {name} الليلة في الحبس، بعيدًا عن الأنياب.",
    seerSees: "{name} هو: {role}.",
    shieldUltimate: "الدرع الأقصى يحيط بالقرية كلها — ويفقد المنقذ قدراته.",
    logShieldUltimate: "الليلة {n}: {name} فعّل الدرع الأقصى.",
    protectedTonight: "{name} محمي هذه الليلة.",
    spyCaught: "لقد كشفك القطيع… لن ترى الفجر.",
    spyHint: "ترى ظلًا: الحرف الأول «{letter}».",
    spyNothing: "لا ترى شيئًا في الظلام.",
    eyesClosed: "تُبقي عينيك مغمضتين.",
    packDisagree: "خلاف في القطيع: تعود الذئاب للنوم، وستحسم الأم الكبرى الأمر.",
    packChose: "اختار القطيع {name}.",
    matriarchImpose: "الأم الكبرى تفرض {name}.",
    logMatriarch: "الأم الكبرى تحسم: {name}.",
    logSoloKill: "{role} يفترس {name} (قطيع منفرد).",
    talkativeWord: "الكلمة المفروضة على الذئب الثرثار: «{word}». عليه قولها خلال النقاش.",
    infectBlocked: "فشل التحويل: الهدف محمي.",
    logInfectBlocked: "المنقذ أوقف التحويل — القدرة محفوظة.",
    infectJoin: "{name} ينضم إلى القطيع محتفظًا بقدرته.",
    logInfect: "الذئب الأسود يحوّل {name}.",
    silenceNote: "{name} لن يتمكن من النقاش صباح الغد.",
    logSilence: "الذئب الأسود يُسكت {name}.",
    packAsPlanned: "القطيع يفترس كما هو مقرر.",
    whiteTarget: "سيفترس الذئب الأبيض {name}.",
    witchSaved: "تم إنقاذ ضحية الذئاب.",
    poisoned: "{name} مسموم.",
    fluteCharm: "اللحن يسحر روحين جديدتين.",
    ravenVotes: "سيبدأ {name} التصويت بصوتين.",
    tavernDrink: "شرب {name}: غدًا لا يمكنه التصويت، لكنه محصّن.",
    bearGrowl: "🐻 الدب يزمجر.",
    bearCalm: "كل شيء على ما يرام.",
    generalWolf: "{name} كان ذئبًا: تم إسقاطه. {actor} يصبح القائد الجديد.",
    logGeneralWolf: "الجنرال يقتل {name} ويصبح قائدًا.",
    generalFail: "{name} لم يكن ذئبًا: سيد اللعبة يقصي الجنرال.",
    logGeneralFail: "فشلت ضربة الجنرال على {name}.",
    generalIdle: "الجنرال لا يتحرك هذه الليلة.",
    survivedAttack: "نجا {name} من الهجوم… هذه المرة.",
    deathLine: "مات {name} — {cause}.",
    logDeath: "{name} ({role}) — {cause}.",
    elderFall: "سقط الشيخ بيد القرية: يفقد جميع القرويين قدراتهم.",
    wildAwaken: "يشعر {name} بالوحش يستيقظ في داخله…",
    redRidingHood: "ذات الرداء الأحمر بقيت تحت حماية الصياد: فشل الهجوم.",
    villageShieldSaved: "🛡️ الدرع الأقصى حمى القرية كلها هذه الليلة.",
    saviorFoiled: "المنقذ أفشل هجوم الذئاب.",
    jailerSafe: "سجين السجّان كان بعيدًا عن المنال.",
    bearNear: "🐻 الدب يزمجر: هناك ذئب قريب جدًا!",
    mutedToday: "{name} صامت: لا يمكنه النقاش اليوم.",
    nobodyDied: "بشكل غريب، لم يمت أحد هذه الليلة.",
    newCaptain: "{name} يصبح القائد الجديد.",
    day1NoVote: "اليوم 1: رفضت القرية التصويت.",
    logTalkativeExecuted: "اليوم {d} — أُعدم الذئب الثرثار (لم يقل الكلمة)؛ أُلغي التصويت.",
    nightHeader: "— الليلة {n} —",
    killerFallback: "الليلة {n}: لا ذئب عادي — القتل يعود إلى {role}.",
    idiotSurvives: "{name} هو أبله القرية: ينجو لكنه يفقد حق التصويت.",
    untouchableToday: "{name} كان محصّنًا اليوم.",
    winAngel: "{name} — الملاك يفوز: أعدمته القرية في اليوم الأول.",
    winNobody: "لا أحد ينجو. انطفأت القرية.",
    winLovers: "العاشقان يفوزان: {a} و {b}.",
    winWhiteWolf: "الذئب الأبيض {name} يبقى وحده: فوز منفرد.",
    winPiper: "عازف المزمار {name} سحر القرية بأكملها.",
    winVillage: "القرية تنتصر: لم يبق أي ذئب.",
    winWolves: "الذئاب المستذئبة افترست القرية.",
    thiefSteal: "تسرق دور {name}: {role}. يصبح {name} قرويًا بسيطًا.",
    logThiefSteal: "اللص يسرق دور {name} ({role}).",
    facesProtectMsg: "الوجوه الثلاثة تحمي {name} هذه الليلة.",
    facesInspectMsg: "الوجوه الثلاثة تكتشف: {name} هو {role}.",
    facesLifeMsg: "الوجوه الثلاثة تستعمل جرعة الحياة: تم إنقاذ ضحية الذئاب.",
    facesPoisonMsg: "الوجوه الثلاثة تسمّم {name}.",
    logFaces: "الوجوه الثلاثة تستعمل «{power}» على {name}.",
    maniacTargetMsg: "المهووس يضرب {name} — لا حماية توقفه.",
    logManiac: "المهووس يغتال {name}.",
    winManiac: "المهووس {name} يبقى سيد القرية: فوز منفرد.",
    repWolvesTarget: "🐺 قطيع الذئاب ← {name}",
    repNoWolvesTarget: "🐺 قطيع الذئاب ← بلا ضحية",
    repManiacTarget: "🔪 المهووس ← {name} (هجوم لا يُوقف)",
    repSeerCheck: "🔮 {role} يكشف {name} ← {result}",
    repProtect: "🛡️ {role} يحمي {name}",
    repVillageShield: "🛡️ الدرع الأقصى: القرية كلها محمية",
    repWitchLife: "⚗️ استُعملت جرعة الحياة على {name}",
    repWitchPoison: "☠️ استُعملت جرعة السم على {name}",
    repSilence: "🤐 الذئب الأسود يُسكت {name}",
    repSilenceSelf: "🤐 الذئب الأسود يُسكت نفسه ({name})",
    repInfect: "🩸 الذئب الأسود يحوّل {name}",
    repThief: "🎭 اللص ({thief}) يسرق دور {name} ← {role}؛ يصبح {name} قرويًا بسيطًا",
    repFaces: "🎭 الوجوه الثلاثة تستعمل «{power}» على {name}",
    repDied: "💀 {name} ({role}) — {cause}",
    repSavedBy: "✨ {name} أنقذه {role}",
    repMuted: "🤐 {name} لا يمكنه النقاش اليوم",
    repNoDeaths: "لم يمت أحد هذه الليلة.",
    repFacePower_protect: "الحماية",
    repFacePower_life: "جرعة الحياة",
    repFacePower_poison: "جرعة السم",
    repFacePower_inspect: "الكشف",
    cause_MANIAC: "اغتاله المهووس",
    cause_SUICIDE_REVEAL: "انتحار / كشف الدور",
    logSuicideReveal: "كشف {name} هويته: انتحار فوري.",
    cause_THREE_FACES_POISON: "سمّمه صاحب الوجوه الثلاثة",
    cause_WOLVES: "افترسته الذئاب",
    cause_WITCH_POISON: "سمّمته الساحرة",
    cause_WHITE_WOLF_KILL: "ذبحه الذئب الأبيض",
    cause_HUNTER_SHOT: "أطلق عليه الصياد النار",
    cause_HEARTBREAK: "مات من الحزن",
    cause_VILLAGE_VOTE: "أعدمته القرية",
    cause_JAILER_EXECUTION: "أعدمه السجّان",
    cause_SPY_DETECTED: "كشفه القطيع",
    cause_TALKATIVE_WOLF: "خانه صمته",
    cause_GENERAL_STRIKE: "أسقطه الجنرال",
    cause_GENERAL_FAILED: "أقصاه سيد اللعبة (ضربة الجنرال الفاشلة)",
    puppetSaved: "تعرّض {name} للهجوم، لكن الدُمية امتصّت الضربة! ينجو من الموت ولكنه يُمنع من الكلام خلال نقاش اليوم.",
    repPuppetSaved: "🎭 {name} (محرّك الدمى) امتص الهجوم بفضل دمية ويُمنع من الكلام.",
  },
  es: {
    logVoteTally: "Día {d} — Voto: [{tally}] → Eliminado(s): {names}",
    lovers: "{a} y {b} ahora son amantes.",
    logCupid: "Cupido une a {a} y {b}.",
    mimeCopy: "Copias el rol: {role}.",
    wildModel: "Tu modelo es {name}.",
    jailExecuted: "{name} es ejecutado en su celda.",
    jailLocked: "{name} pasa la noche bajo llave, a salvo de los colmillos.",
    seerSees: "{name} es: {role}.",
    shieldUltimate: "El Escudo Definitivo envuelve toda la aldea — el Salvador pierde sus poderes.",
    logShieldUltimate: "Noche {n}: Escudo Definitivo activado por {name}.",
    protectedTonight: "{name} está protegido esta noche.",
    spyCaught: "La manada te ha descubierto… no verás el amanecer.",
    spyHint: "Vislumbras una silueta: inicial «{letter}».",
    spyNothing: "No ves nada en la oscuridad.",
    eyesClosed: "Mantienes los ojos cerrados.",
    packDisagree: "Desacuerdo en la manada: los lobos vuelven a dormir, la Matriarca decidirá.",
    packChose: "La manada ha elegido a {name}.",
    matriarchImpose: "La Matriarca impone a {name}.",
    logMatriarch: "La Matriarca decide: {name}.",
    logSoloKill: "{role} devora a {name} (manada solitaria).",
    talkativeWord: "Palabra secreta para el Lobo Charlatán: «{word}». Debe decirla durante el debate.",
    infectBlocked: "La infección falla: el objetivo está protegido.",
    logInfectBlocked: "Infección bloqueada por el Salvador — poder conservado.",
    infectJoin: "{name} se une a la manada conservando su poder.",
    logInfect: "El Lobo Negro infecta a {name}.",
    silenceNote: "{name} no podrá debatir mañana por la mañana.",
    logSilence: "El Lobo Negro silencia a {name}.",
    packAsPlanned: "La manada devora según lo previsto.",
    whiteTarget: "{name} será devorado por el Lobo Blanco.",
    witchSaved: "La víctima de los lobos ha sido salvada.",
    poisoned: "{name} está envenenado.",
    fluteCharm: "La melodía hechiza a dos nuevas almas.",
    ravenVotes: "{name} comenzará la votación con 2 votos.",
    tavernDrink: "{name} bebió: mañana no podrá votar, pero será intocable.",
    bearGrowl: "🐻 El Oso gruñe.",
    bearCalm: "Todo está tranquilo.",
    generalWolf: "{name} era un Lobo: ha sido abatido. {actor} se convierte en el nuevo Capitán.",
    logGeneralWolf: "El General abate a {name} y se convierte en Capitán.",
    generalFail: "{name} no era un Lobo: el General es eliminado por el Director de Juego.",
    logGeneralFail: "El disparo del General falla en {name}.",
    generalIdle: "El General no actúa esta noche.",
    survivedAttack: "{name} sobrevivió al ataque… por esta vez.",
    deathLine: "{name} ha muerto — {cause}.",
    logDeath: "{name} ({role}) — {cause}.",
    elderFall: "El Anciano cayó a manos de la aldea: todos los aldeanos pierden sus poderes.",
    wildAwaken: "{name} siente que la bestia despierta en su interior…",
    redRidingHood: "Caperucita Roja se quedó bajo la guardia del Cazador: el ataque falla.",
    villageShieldSaved: "🛡️ El Escudo Definitivo protegió a toda la aldea esta noche.",
    saviorFoiled: "El Salvador frustró el ataque de los lobos.",
    jailerSafe: "El prisionero del Carcelero estaba fuera de alcance.",
    bearNear: "🐻 El oso gruñe: ¡un lobo está muy cerca!",
    mutedToday: "{name} está silenciado: no puede debatir hoy.",
    nobodyDied: "Extrañamente, nadie murió esta noche.",
    newCaptain: "{name} se convierte en el nuevo Capitán.",
    day1NoVote: "Día 1: la aldea se negó a votar.",
    logTalkativeExecuted: "Día {d} — Lobo Charlatán ejecutado (no dijo la palabra); votación cancelada.",
    nightHeader: "— Noche {n} —",
    killerFallback: "Noche {n}: sin lobo estándar — la matanza recae en {role}.",
    idiotSurvives: "{name} es el Tonto del Pueblo: sobrevive pero pierde su derecho a voto.",
    untouchableToday: "{name} era intocable hoy.",
    winAngel: "{name} — el Ángel gana: la aldea lo ejecutó el primer día.",
    winNobody: "Nadie sobrevive. La aldea se ha extinguido.",
    winLovers: "Los Amantes ganan: {a} y {b}.",
    winWhiteWolf: "El Lobo Blanco {name} queda solo: victoria solitaria.",
    winPiper: "El Flautista {name} hechizó a toda la aldea.",
    winVillage: "La Aldea triunfa: ya no acecha ningún lobo.",
    winWolves: "Los Hombres Lobo han devorado la aldea.",
    thiefSteal: "Robas el rol de {name}: {role}. {name} se convierte en un simple Aldeano.",
    logThiefSteal: "El Ladrón roba el rol de {name} ({role}).",
    facesProtectMsg: "3 caras protege a {name} esta noche.",
    facesInspectMsg: "3 caras descubre: {name} es {role}.",
    facesLifeMsg: "3 caras usa la poción de vida: la víctima de los lobos es salvada.",
    facesPoisonMsg: "3 caras envenena a {name}.",
    logFaces: "3 caras usa el rostro «{power}» en {name}.",
    maniacTargetMsg: "El Maníaco ataca a {name} — ninguna protección puede detenerlo.",
    logManiac: "El Maníaco asesina a {name}.",
    winManiac: "El Maníaco {name} domina lo que queda de la aldea: victoria solitaria.",
    repWolvesTarget: "🐺 Manada de Lobos → {name}",
    repNoWolvesTarget: "🐺 Manada de Lobos → sin víctima",
    repManiacTarget: "🔪 Maníaco → {name} (ataque imparable)",
    repSeerCheck: "🔮 {role} inspecciona a {name} → {result}",
    repProtect: "🛡️ {role} protege a {name}",
    repVillageShield: "🛡️ Escudo Definitivo: aldea entera protegida",
    repWitchLife: "⚗️ Poción de vida usada en {name}",
    repWitchPoison: "☠️ Poción de muerte usada en {name}",
    repSilence: "🤐 Lobo Negro silencia a {name}",
    repSilenceSelf: "🤐 Lobo Negro se silencia a sí mismo ({name})",
    repInfect: "🩸 Lobo Negro infecta a {name}",
    repThief: "🎭 El Ladrón ({thief}) roba el rol de {name} → {role} ; {name} se convierte en Aldeano",
    repFaces: "🎭 3 caras usa «{power}» en {name}",
    repDied: "💀 {name} ({role}) — {cause}",
    repSavedBy: "✨ {name} salvado por {role}",
    repMuted: "🤐 {name} no puede debatir hoy",
    repNoDeaths: "Nadie murió esta noche.",
    repFacePower_protect: "Protección",
    repFacePower_life: "Poción de vida",
    repFacePower_poison: "Poción de muerte",
    repFacePower_inspect: "Inspección",
    cause_MANIAC: "asesinado por el Maníaco",
    cause_SUICIDE_REVEAL: "Suicidio / revelación de rol",
    logSuicideReveal: "{name} reveló su identidad: suicidio inmediato.",
    cause_THREE_FACES_POISON: "envenenado por 3 caras",
    cause_WOLVES: "devorado por los lobos",
    cause_WITCH_POISON: "envenenado por la Bruja",
    cause_WHITE_WOLF_KILL: "degollado por el Lobo Blanco",
    cause_HUNTER_SHOT: "abatido por el Cazador",
    cause_HEARTBREAK: "murió de pena",
    cause_VILLAGE_VOTE: "ejecutado por la aldea",
    cause_JAILER_EXECUTION: "ejecutado por el Carcelero",
    cause_SPY_DETECTED: "descubierto por la manada",
    cause_TALKATIVE_WOLF: "traicionado por su silencio",
    cause_GENERAL_STRIKE: "abatido por el General",
    cause_GENERAL_FAILED: "eliminado por el Director de Juego (fallo del General)",
    puppetSaved: "{name} fue atacado(a), pero su marioneta absorbió el golpe. Sobrevive, pero es silenciado(a) para el debate de hoy.",
    repPuppetSaved: "🎭 {name} (Titiritero) absorbió el ataque con su marioneta y está silenciado(a).",
  },
  pt: {
    logVoteTally: "Dia {d} — Votação: [{tally}] → Eliminado(s): {names}",
    lovers: "{a} e {b} agora são amantes.",
    logCupid: "Cupido une {a} e {b}.",
    mimeCopy: "Copiaste o papel: {role}.",
    wildModel: "O teu modelo é {name}.",
    jailExecuted: "{name} é executado na cela.",
    jailLocked: "{name} passa a noite trancado, a salvo das presas.",
    seerSees: "{name} é: {role}.",
    shieldUltimate: "O Escudo Supremo envolve toda a aldeia — o Salvador perde os seus poderes.",
    logShieldUltimate: "Noite {n}: Escudo Supremo ativado por {name}.",
    protectedTonight: "{name} está protegido esta noite.",
    spyCaught: "A alcateia descobriu-te… não verás o amanhecer.",
    spyHint: "Vislumbras uma silhueta: inicial «{letter}».",
    spyNothing: "Não vês nada na escuridão.",
    eyesClosed: "Manténs os olhos fechados.",
    packDisagree: "Desacordo na alcateia: os lobos voltam a dormir, a Matriarca decidirá.",
    packChose: "A alcateia escolheu {name}.",
    matriarchImpose: "A Matriarca impõe {name}.",
    logMatriarch: "A Matriarca decide: {name}.",
    logSoloKill: "{role} devora {name} (alcateia solitária).",
    talkativeWord: "Palavra secreta para o Lobo Falador: «{word}». Ele deve dizê-la durante o debate.",
    infectBlocked: "A infeção falha: o alvo está protegido.",
    logInfectBlocked: "Infeção bloqueada pelo Salvador — poder conservado.",
    infectJoin: "{name} junta-se à alcateia conservando o seu poder.",
    logInfect: "O Lobo Negro infeta {name}.",
    silenceNote: "{name} não poderá debater amanhã de manhã.",
    logSilence: "O Lobo Negro silencia {name}.",
    packAsPlanned: "A alcateia devora como planeado.",
    whiteTarget: "{name} será devorado pelo Lobo Branco.",
    witchSaved: "A vítima dos lobos foi salva.",
    poisoned: "{name} está envenenado.",
    fluteCharm: "A melodia enfeitiça duas novas almas.",
    ravenVotes: "{name} começará a votação com 2 votos.",
    tavernDrink: "{name} bebeu: amanhã não poderá votar, mas será intocável.",
    bearGrowl: "🐻 O Urso rosna.",
    bearCalm: "Tudo está calmo.",
    generalWolf: "{name} era um Lobo: foi abatido. {actor} torna-se o novo Capitão.",
    logGeneralWolf: "O General abate {name} e torna-se Capitão.",
    generalFail: "{name} não era um Lobo: o General é eliminado pelo Mestre de Jogo.",
    logGeneralFail: "O tiro do General falha em {name}.",
    generalIdle: "O General não atua esta noite.",
    survivedAttack: "{name} sobreviveu ao ataque… desta vez.",
    deathLine: "{name} morreu — {cause}.",
    logDeath: "{name} ({role}) — {cause}.",
    elderFall: "O Ancião caiu às mãos da aldeia: todos os aldeões perdem os seus poderes.",
    wildAwaken: "{name} sente a besta a despertar no seu interior…",
    redRidingHood: "O Capuchinho Vermelho ficou sob a guarda do Caçador: o ataque falha.",
    villageShieldSaved: "🛡️ O Escudo Supremo protegeu toda a aldeia esta noite.",
    saviorFoiled: "O Salvador impediu o ataque dos lobos.",
    jailerSafe: "O prisioneiro do Carcereiro estava fora de alcance.",
    bearNear: "🐻 O urso rosna: um lobo está muito perto!",
    mutedToday: "{name} está silenciado: não pode debater hoje.",
    nobodyDied: "Estranhamente, ninguém morreu esta noite.",
    newCaptain: "{name} torna-se o novo Capitão.",
    day1NoVote: "Dia 1: a aldeia recusou-se a votar.",
    logTalkativeExecuted: "Dia {d} — Lobo Falador executado (não disse a palavra); votação cancelada.",
    nightHeader: "— Noite {n} —",
    killerFallback: "Noite {n}: sem lobo padrão — a morte recai em {role}.",
    idiotSurvives: "{name} é o Idiota da Aldeia: sobrevive mas perde o seu direito de voto.",
    untouchableToday: "{name} era intocável hoje.",
    winAngel: "{name} — o Anjo ganha: a aldeia executou-o no primeiro dia.",
    winNobody: "Ninguém sobrevive. A aldeia extinguiu-se.",
    winLovers: "Os Amantes ganham: {a} e {b}.",
    winWhiteWolf: "O Lobo Branco {name} fica sozinho: vitória solitária.",
    winPiper: "O Flautista {name} enfeitiçou toda a aldeia.",
    winVillage: "A Aldeia triunfa: nenhum lobo ronda mais.",
    winWolves: "Os Lobisomens devoraram a aldeia.",
    thiefSteal: "Roubas o papel de {name}: {role}. {name} torna-se um simples Aldeão.",
    logThiefSteal: "O Ladrão rouba o papel de {name} ({role}).",
    facesProtectMsg: "3 faces protege {name} esta noite.",
    facesInspectMsg: "3 faces descobre: {name} é {role}.",
    facesLifeMsg: "3 faces usa a poção de vida: a vítima dos lobos é salva.",
    facesPoisonMsg: "3 faces envenena {name}.",
    logFaces: "3 faces usa o rosto «{power}» em {name}.",
    maniacTargetMsg: "O Maníaco ataca {name} — nenhuma proteção pode detê-lo.",
    logManiac: "O Maníaco assassina {name}.",
    winManiac: "O Maníaco {name} domina o que resta da aldeia: vitória solitária.",
    repWolvesTarget: "🐺 Alcateia de Lobos → {name}",
    repNoWolvesTarget: "🐺 Alcateia de Lobos → sem vítima",
    repManiacTarget: "🔪 Maníaco → {name} (ataque imparável)",
    repSeerCheck: "🔮 {role} inspeciona {name} → {result}",
    repProtect: "🛡️ {role} protege {name}",
    repVillageShield: "🛡️ Escudo Supremo: aldeia inteira protegida",
    repWitchLife: "⚗️ Poção de vida usada em {name}",
    repWitchPoison: "☠️ Poção de morte usada em {name}",
    repSilence: "🤐 Lobo Negro silencia {name}",
    repSilenceSelf: "🤐 Lobo Negro silencia-se a si próprio ({name})",
    repInfect: "🩸 Lobo Negro infeta {name}",
    repThief: "🎭 O Ladrão ({thief}) rouba o papel de {name} → {role} ; {name} torna-se Aldeão",
    repFaces: "🎭 3 faces usa «{power}» em {name}",
    repDied: "💀 {name} ({role}) — {cause}",
    repSavedBy: "✨ {name} salvo por {role}",
    repMuted: "🤐 {name} não pode debater hoje",
    repNoDeaths: "Ninguém morreu esta noite.",
    repFacePower_protect: "Proteção",
    repFacePower_life: "Poção de vida",
    repFacePower_poison: "Poção de morte",
    repFacePower_inspect: "Inspeção",
    cause_MANIAC: "assassinado pelo Maníaco",
    cause_SUICIDE_REVEAL: "Suicídio / revelação de papel",
    logSuicideReveal: "{name} revelou a sua identidade: suicídio imediato.",
    cause_THREE_FACES_POISON: "envenenado por 3 faces",
    cause_WOLVES: "devorado pelos lobos",
    cause_WITCH_POISON: "envenenado pela Bruxa",
    cause_WHITE_WOLF_KILL: "degolado pelo Lobo Branco",
    cause_HUNTER_SHOT: "abatido pelo Caçador",
    cause_HEARTBREAK: "morreu de desgosto",
    cause_VILLAGE_VOTE: "executado pela aldeia",
    cause_JAILER_EXECUTION: "executado pelo Carcereiro",
    cause_SPY_DETECTED: "descoberto pela alcateia",
    cause_TALKATIVE_WOLF: "traído pelo seu silêncio",
    cause_GENERAL_STRIKE: "abatido pelo General",
    cause_GENERAL_FAILED: "eliminado pelo Mestre de Jogo (falha do General)",
    puppetSaved: "{name} foi atacado(a), mas sua marionete absorveu o golpe! Sobrevive, mas está silenciado(a) para o debate de hoje.",
    repPuppetSaved: "🎭 {name} (Marionetista) absorveu o ataque usando sua marionete e está silenciado(a).",
  },
  ru: {
    logVoteTally: "День {d} — Голосование: [{tally}] → Исключен(ы): {names}",
    lovers: "{a} и {b} теперь влюблены.",
    logCupid: "Купидон связывает {a} и {b}.",
    mimeCopy: "Вы копируете роль: {role}.",
    wildModel: "Ваш кумир — {name}.",
    jailExecuted: "{name} казнен в камере.",
    jailLocked: "{name} проводит ночь взаперти, в безопасности от клыков.",
    seerSees: "{name} — {role}.",
    shieldUltimate: "Абсолютный Щит закрывает всю деревню — Спаситель теряет свои силы.",
    logShieldUltimate: "Ночь {n}: Абсолютный Щит активирован игроком {name}.",
    protectedTonight: "{name} под защитой этой ночью.",
    spyCaught: "Стая заметила вас… вы не увидите рассвета.",
    spyHint: "Вы замечаете силуэт: буква «{letter}».",
    spyNothing: "Вы ничего не видите в темноте.",
    eyesClosed: "Вы держите глаза закрытыми.",
    packDisagree: "Разногласия в стае: волки засыпают, решение примет Матриарх.",
    packChose: "Стая выбрала {name}.",
    matriarchImpose: "Матриарх настаивает на {name}.",
    logMatriarch: "Матриарх решает: {name}.",
    logSoloKill: "{role} пожирает {name} (одинокий волк).",
    talkativeWord: "Тайное слово для Болтливого Волка: «{word}». Он должен произнести его днем.",
    infectBlocked: "Заражение не удалось: цель защищена.",
    logInfectBlocked: "Заражение заблокировано Спасителем — сила сохранена.",
    infectJoin: "{name} присоединяется к стае, сохраняя свою силу.",
    logInfect: "Черный Волк заражает {name}.",
    silenceNote: "{name} не сможет говорить завтра утром.",
    logSilence: "Черный Волк заставляет замолчать {name}.",
    packAsPlanned: "Стая пожирает, как и планировалось.",
    whiteTarget: "{name} будет растерзан Белым Волком.",
    witchSaved: "Жертва волков спасена.",
    poisoned: "{name} отравлен.",
    fluteCharm: "Мелодия очаровывает еще две души.",
    ravenVotes: "{name} начнет голосование с 2 голосами.",
    tavernDrink: "{name} выпил: завтра он не голосует, но неприкосновенен.",
    bearGrowl: "🐻 Медведь рычит.",
    bearCalm: "Все спокойно.",
    generalWolf: "{name} был Волком: он застрелен. {actor} становится новым Капитаном.",
    logGeneralWolf: "Генерал убивает {name} и становится Капитаном.",
    generalFail: "{name} не был Волком: Генерал устранен Ведущим.",
    logGeneralFail: "Выстрел Генерала не удался на {name}.",
    generalIdle: "Генерал бездействует этой ночью.",
    survivedAttack: "{name} пережил атаку… на этот раз.",
    deathLine: "{name} мертв — {cause}.",
    logDeath: "{name} ({role}) — {cause}.",
    elderFall: "Старейшина пал от рук деревни: все жители теряют свои силы.",
    wildAwaken: "{name} чувствует, как зверь просыпается внутри…",
    redRidingHood: "Красная Шапочка осталась под защитой Охотника: атака не удалась.",
    villageShieldSaved: "🛡️ Абсолютный Щит защитил всю деревню этой ночью.",
    saviorFoiled: "Спаситель сорвал атаку волков.",
    jailerSafe: "Пленник Тюремщика был недосягаем.",
    bearNear: "🐻 Медведь рычит: волк совсем близко!",
    mutedToday: "{name} онемел: он не может спорить сегодня.",
    nobodyDied: "Странно, но никто не умер этой ночью.",
    newCaptain: "{name} становится новым Капитаном.",
    day1NoVote: "День 1: деревня отказалась голосовать.",
    logTalkativeExecuted: "День {d} — Болтливый Волк казнен (слово не названо); голосование отменено.",
    nightHeader: "— Ночь {n} —",
    killerFallback: "Ночь {n}: нет обычных волков — убийство поручается {role}.",
    idiotSurvives: "{name} — Деревенский Дурак: он выживает, но теряет право голоса.",
    untouchableToday: "{name} был неприкосновенен сегодня.",
    winAngel: "{name} — Ангел побеждает: деревня казнила его в первый день.",
    winNobody: "Никто не выжил. Деревня вымерла.",
    winLovers: "Влюбленные побеждают: {a} и {b}.",
    winWhiteWolf: "Белый Волк {name} остается один: одиночная победа.",
    winPiper: "Флейтист {name} очаровал всю деревню.",
    winVillage: "Деревня торжествует: волки больше не бродят.",
    winWolves: "Оборотни сожрали деревню.",
    thiefSteal: "Вы крадете роль {name}: {role}. {name} становится простым жителем.",
    logThiefSteal: "Вор крадет роль {name} ({role}).",
    facesProtectMsg: "3 лица защищают {name} этой ночью.",
    facesInspectMsg: "3 лица узнают: {name} — {role}.",
    facesLifeMsg: "3 лица используют зелье жизни: жертва волков спасена.",
    facesPoisonMsg: "3 лица отравляют {name}.",
    logFaces: "3 лица используют лик «{power}» на {name}.",
    maniacTargetMsg: "Маньяк бьет {name} — никакая защита не спасет.",
    logManiac: "Маньяк убивает {name}.",
    winManiac: "Маньяк {name} правит остатками деревни: одиночная победа.",
    repWolvesTarget: "🐺 Стая оборотней → {name}",
    repNoWolvesTarget: "🐺 Стая оборотней → нет жертвы",
    repManiacTarget: "🔪 Маньяк → {name} (неотразимая атака)",
    repSeerCheck: "🔮 {role} проверяет {name} → {result}",
    repProtect: "🛡️ {role} защищает {name}",
    repVillageShield: "🛡️ Абсолютный Щит: вся деревня защищена",
    repWitchLife: "⚗️ Зелье жизни использовано на {name}",
    repWitchPoison: "☠️ Зелье смерти использовано на {name}",
    repSilence: "🤐 Черный Волк заставляет замолчать {name}",
    repSilenceSelf: "🤐 Черный Волк заставляет замолчать себя ({name})",
    repInfect: "🩸 Черный Волк заражает {name}",
    repThief: "🎭 Вор ({thief}) крадет роль {name} → {role} ; {name} становится жителем",
    repFaces: "🎭 3 лица используют «{power}» на {name}",
    repDied: "💀 {name} ({role}) — {cause}",
    repSavedBy: "✨ {name} спасен {role}",
    repMuted: "🤐 {name} не может говорить сегодня",
    repNoDeaths: "Никто не умер этой ночью.",
    repFacePower_protect: "Защита",
    repFacePower_life: "Зелье жизни",
    repFacePower_poison: "Зелье смерти",
    repFacePower_inspect: "Проверка",
    cause_MANIAC: "убит Маньяком",
    cause_SUICIDE_REVEAL: "Суицид / раскрытие роли",
    logSuicideReveal: "{name} раскрыл свою личность: немедленный суицид.",
    cause_THREE_FACES_POISON: "отравлен 3 лицами",
    cause_WOLVES: "растерзан волками",
    cause_WITCH_POISON: "отравлен Ведьмой",
    cause_WHITE_WOLF_KILL: "зарезан Белым Волком",
    cause_HUNTER_SHOT: "застрелен Охотником",
    cause_HEARTBREAK: "умер от горя",
    cause_VILLAGE_VOTE: "казнен деревней",
    cause_JAILER_EXECUTION: "казнен Тюремщиком",
    cause_SPY_DETECTED: "замечен стаей",
    cause_TALKATIVE_WOLF: "выдан своим молчанием",
    cause_GENERAL_STRIKE: "застрелен Генералом",
    cause_GENERAL_FAILED: "устранен Ведущим (промах Генерала)",
    puppetSaved: "{name} подвергся нападению, но его кукла приняла удар на себя! Он выживает, но лишается голоса на сегодняшнем обсуждении.",
    repPuppetSaved: "🎭 {name} (Кукловод) поглотил атаку с помощью куклы и лишен голоса.",
  },
  zh: {
    logVoteTally: "第 {d} 天 — 投票：[{tally}] → 淘汰：{names}",
    lovers: "{a} 和 {b} 现在是恋人了。",
    logCupid: "丘比特连接了 {a} 和 {b}。",
    mimeCopy: "你复制了角色：{role}。",
    wildModel: "你的榜样是 {name}。",
    jailExecuted: "{name} 在牢房中被处决。",
    jailLocked: "{name} 被关在牢里过夜，免受狼牙的伤害。",
    seerSees: "{name} 是：{role}。",
    shieldUltimate: "终极护盾保护了整个村庄 — 守卫失去了能力。",
    logShieldUltimate: "第 {n} 夜：{name} 激活了终极护盾。",
    protectedTonight: "{name} 今晚受到保护。",
    spyCaught: "狼群发现了你…你见不到明天的太阳了。",
    spyHint: "你瞥见了一个轮廓：首字母“{letter}”。",
    spyNothing: "你在黑暗中什么也没看到。",
    eyesClosed: "你闭着眼睛。",
    packDisagree: "狼群内部产生分歧：狼人们重新入睡，将由头狼(母狼)决定。",
    packChose: "狼群选择了 {name}。",
    matriarchImpose: "头狼强制选择 {name}。",
    logMatriarch: "头狼决定：{name}。",
    logSoloKill: "{role} 吞食了 {name}（独狼）。",
    talkativeWord: "多嘴狼的秘密词汇：“{word}”。他必须在讨论期间说出它。",
    infectBlocked: "感染失败：目标受到保护。",
    logInfectBlocked: "感染被守卫阻止 — 技能保留。",
    infectJoin: "{name} 加入狼群并保留其技能。",
    logInfect: "黑狼感染了 {name}。",
    silenceNote: "{name} 明天早上将无法发言。",
    logSilence: "黑狼让 {name} 禁言。",
    packAsPlanned: "狼群按计划吞食。",
    whiteTarget: "{name} 将被白狼吞食。",
    witchSaved: "狼群的受害者得救了。",
    poisoned: "{name} 被毒死了。",
    fluteCharm: "旋律又迷惑了两个灵魂。",
    ravenVotes: "{name} 投票时将自带2票。",
    tavernDrink: "{name} 喝醉了：明天无法投票，但免疫一切伤害。",
    bearGrowl: "🐻 熊咆哮了。",
    bearCalm: "一切安好。",
    generalWolf: "{name} 是狼人：被击毙。{actor} 成为新任警长。",
    logGeneralWolf: "将军击毙了 {name} 并成为警长。",
    generalFail: "{name} 不是狼人：将军被法官淘汰。",
    logGeneralFail: "将军对 {name} 的射击失败。",
    generalIdle: "将军今晚没有行动。",
    survivedAttack: "{name} 挺过了攻击… 暂时的。",
    deathLine: "{name} 死了 — {cause}。",
    logDeath: "{name} ({role}) — {cause}。",
    elderFall: "长老死于村庄之手：所有村民失去能力。",
    wildAwaken: "{name} 感觉到体内的野兽在觉醒…",
    redRidingHood: "小红帽在猎人的保护下：攻击失败。",
    villageShieldSaved: "🛡️ 终极护盾今晚保护了整个村庄。",
    saviorFoiled: "守卫挫败了狼人的攻击。",
    jailerSafe: "狱卒的囚犯安然无恙。",
    bearNear: "🐻 熊咆哮了：附近有狼！",
    mutedToday: "{name} 被禁言：今天无法讨论。",
    nobodyDied: "奇怪的是，今晚没人死亡。",
    newCaptain: "{name} 成为新警长。",
    day1NoVote: "第 1 天：村庄拒绝投票。",
    logTalkativeExecuted: "第 {d} 天 — 多嘴狼被处决（未说出词汇）；投票取消。",
    nightHeader: "— 第 {n} 夜 —",
    killerFallback: "第 {n} 夜：没有普通狼人 — 击杀权交给 {role}。",
    idiotSurvives: "{name} 是白痴：幸存但失去投票权。",
    untouchableToday: "{name} 今天不可侵犯。",
    winAngel: "{name} — 天使获胜：村庄在第一天处决了他。",
    winNobody: "无人生还。村庄覆灭。",
    winLovers: "恋人获胜：{a} 和 {b}。",
    winWhiteWolf: "白狼 {name} 屹立不倒：孤狼胜利。",
    winPiper: "吹笛者 {name} 迷惑了整个村庄。",
    winVillage: "村庄胜利：不再有狼人出没。",
    winWolves: "狼人吞噬了村庄。",
    thiefSteal: "你偷了 {name} 的角色：{role}。{name} 变成了普通村民。",
    logThiefSteal: "盗贼偷了 {name} 的角色 ({role})。",
    facesProtectMsg: "三面人今晚保护了 {name}。",
    facesInspectMsg: "三面人发现：{name} 是 {role}。",
    facesLifeMsg: "三面人使用了灵药：狼群的受害者得救了。",
    facesPoisonMsg: "三面人毒死了 {name}。",
    logFaces: "三面人对 {name} 使用了“{power}”面具。",
    maniacTargetMsg: "狂人袭击了 {name} — 任何保护都无法阻止。",
    logManiac: "狂人谋杀了 {name}。",
    winManiac: "狂人 {name} 统治了村庄的废墟：单独获胜。",
    repWolvesTarget: "🐺 狼群 → {name}",
    repNoWolvesTarget: "🐺 狼群 → 无受害者",
    repManiacTarget: "🔪 狂人 → {name} (无法阻挡的攻击)",
    repSeerCheck: "🔮 {role} 查验 {name} → {result}",
    repProtect: "🛡️ {role} 保护 {name}",
    repVillageShield: "🛡️ 终极护盾：全村受保护",
    repWitchLife: "⚗️ 对 {name} 使用了解药",
    repWitchPoison: "☠️ 对 {name} 使用了毒药",
    repSilence: "🤐 黑狼禁言 {name}",
    repSilenceSelf: "🤐 黑狼禁言自己 ({name})",
    repInfect: "🩸 黑狼感染了 {name}",
    repThief: "🎭 盗贼 ({thief}) 偷了 {name} 的角色 → {role}；{name} 变成村民",
    repFaces: "🎭 三面人对 {name} 使用了“{power}”",
    repDied: "💀 {name} ({role}) — {cause}",
    repSavedBy: "✨ {name} 被 {role} 救下",
    repMuted: "🤐 {name} 今天不能发言",
    repNoDeaths: "今晚无人死亡。",
    repFacePower_protect: "保护",
    repFacePower_life: "解药",
    repFacePower_poison: "毒药",
    repFacePower_inspect: "查验",
    cause_MANIAC: "被狂人谋杀",
    cause_SUICIDE_REVEAL: "自杀 / 暴露角色",
    logSuicideReveal: "{name} 暴露了身份：立即自杀。",
    cause_THREE_FACES_POISON: "被三面人毒死",
    cause_WOLVES: "被狼人吞食",
    cause_WITCH_POISON: "被女巫毒死",
    cause_WHITE_WOLF_KILL: "被白狼杀害",
    cause_HUNTER_SHOT: "被猎人射杀",
    cause_HEARTBREAK: "心碎而死",
    cause_VILLAGE_VOTE: "被村庄处决",
    cause_JAILER_EXECUTION: "被狱卒处决",
    cause_SPY_DETECTED: "被狼群发现",
    cause_TALKATIVE_WOLF: "因沉默而暴露",
    cause_GENERAL_STRIKE: "被将军击毙",
    cause_GENERAL_FAILED: "被法官淘汰（将军失误）",
    puppetSaved: "{name} 受到了攻击，但他们的傀儡吸收了伤害！他们幸存下来，但在今天的讨论中被禁言。",
    repPuppetSaved: "🎭 {name} (傀儡师) 使用傀儡吸收了攻击并被禁言。",
  },
  nl: {
    logVoteTally: "Dag {d} — Stemming: [{tally}] → Geëlimineerd: {names}",
    lovers: "{a} en {b} zijn nu geliefden.",
    logCupid: "Cupido verbindt {a} en {b}.",
    mimeCopy: "Je kopieert de rol: {role}.",
    wildModel: "Jouw rolmodel is {name}.",
    jailExecuted: "{name} is geëxecuteerd in de cel.",
    jailLocked: "{name} brengt de nacht achter slot en grendel door, veilig voor de tanden.",
    seerSees: "{name} is: {role}.",
    shieldUltimate: "Het Ultieme Schild beschermt het hele dorp — de Beschermer verliest zijn krachten.",
    logShieldUltimate: "Nacht {n}: Ultieme Schild geactiveerd door {name}.",
    protectedTonight: "{name} is vannacht beschermd.",
    spyCaught: "De roedel heeft je gezien... je zult de ochtend niet halen.",
    spyHint: "Je vangt een glimp op van een silhouet: voorletter “{letter}”.",
    spyNothing: "Je ziet niets in de duisternis.",
    eyesClosed: "Je houdt je ogen gesloten.",
    packDisagree: "Onenigheid in de roedel: de wolven gaan weer slapen, de Matriarch beslist.",
    packChose: "De roedel koos {name}.",
    matriarchImpose: "De Matriarch kiest {name}.",
    logMatriarch: "De Matriarch beslist: {name}.",
    logSoloKill: "{role} verslindt {name} (eenzame wolf).",
    talkativeWord: "Geheim woord voor de Praatgrage Wolf: “{word}”. Hij moet het zeggen tijdens het debat.",
    infectBlocked: "De infectie mislukt: het doelwit is beschermd.",
    logInfectBlocked: "Infectie geblokkeerd door de Beschermer — kracht behouden.",
    infectJoin: "{name} sluit zich aan bij de roedel met behoud van kracht.",
    logInfect: "De Zwarte Wolf infecteert {name}.",
    silenceNote: "{name} mag morgenochtend niet meepraten.",
    logSilence: "De Zwarte Wolf legt {name} het zwijgen op.",
    packAsPlanned: "De roedel verslindt zoals gepland.",
    whiteTarget: "{name} zal worden verslonden door de Witte Wolf.",
    witchSaved: "Het slachtoffer van de wolven is gered.",
    poisoned: "{name} is vergiftigd.",
    fluteCharm: "De melodie betovert twee nieuwe zielen.",
    ravenVotes: "{name} begint de stemming met 2 stemmen.",
    tavernDrink: "{name} heeft gedronken: morgen kan hij niet stemmen, maar hij is onschendbaar.",
    bearGrowl: "🐻 De Beer gromt.",
    bearCalm: "Alles is rustig.",
    generalWolf: "{name} was een Wolf: neergeschoten. {actor} wordt de nieuwe Kapitein.",
    logGeneralWolf: "De Generaal schiet {name} neer en wordt Kapitein.",
    generalFail: "{name} was geen Wolf: de Generaal wordt geëlimineerd door de Spelleider.",
    logGeneralFail: "Het schot van de Generaal op {name} mislukt.",
    generalIdle: "De Generaal komt vannacht niet in actie.",
    survivedAttack: "{name} heeft de aanval overleefd... voor deze keer.",
    deathLine: "{name} is dood — {cause}.",
    logDeath: "{name} ({role}) — {cause}.",
    elderFall: "De Oudste is gevallen door het dorp: alle dorpelingen verliezen hun krachten.",
    wildAwaken: "{name} voelt het beest in zich ontwaken...",
    redRidingHood: "Roodkapje bleef onder de hoede van de Jager: de aanval mislukt.",
    villageShieldSaved: "🛡️ Het Ultieme Schild beschermde het hele dorp vannacht.",
    saviorFoiled: "De Beschermer heeft de aanval van de wolven verijdeld.",
    jailerSafe: "De gevangene van de Cipier was buiten bereik.",
    bearNear: "🐻 De beer gromt: er is een wolf heel dichtbij!",
    mutedToday: "{name} is gemute: hij kan vandaag niet meediscussiëren.",
    nobodyDied: "Vreemd genoeg stierf er vannacht niemand.",
    newCaptain: "{name} wordt de nieuwe Kapitein.",
    day1NoVote: "Dag 1: het dorp weigerde te stemmen.",
    logTalkativeExecuted: "Dag {d} — Praatgrage Wolf geëxecuteerd (woord niet gezegd); stemming geannuleerd.",
    nightHeader: "— Nacht {n} —",
    killerFallback: "Nacht {n}: geen standaard wolf — de moord gaat naar de {role}.",
    idiotSurvives: "{name} is de Dorpsgek: hij overleeft maar verliest zijn stemrecht.",
    untouchableToday: "{name} was onschendbaar vandaag.",
    winAngel: "{name} — de Engel wint: het dorp executeerde hem op de eerste dag.",
    winNobody: "Niemand overleeft. Het dorp is uitgestorven.",
    winLovers: "De Geliefden winnen: {a} & {b}.",
    winWhiteWolf: "De Witte Wolf {name} staat alleen: eenzame overwinning.",
    winPiper: "De Fluitspeler {name} betoverde het hele dorp.",
    winVillage: "Het Dorp zegeviert: er sluipen geen wolven meer rond.",
    winWolves: "De Weerwolven hebben het dorp verslonden.",
    thiefSteal: "Je steelt de rol van {name}: {role}. {name} wordt een gewone Dorpeling.",
    logThiefSteal: "De Dief steelt de rol van {name} ({role}).",
    facesProtectMsg: "3 gezichten beschermt {name} vannacht.",
    facesInspectMsg: "3 gezichten ontdekt: {name} is {role}.",
    facesLifeMsg: "3 gezichten gebruikt het levensdrankje: het slachtoffer is gered.",
    facesPoisonMsg: "3 gezichten vergiftigt {name}.",
    logFaces: "3 gezichten gebruikt het gezicht “{power}” op {name}.",
    maniacTargetMsg: "De Maniakaal valt {name} aan — geen bescherming kan het stoppen.",
    logManiac: "De Maniakaal vermoordt {name}.",
    winManiac: "De Maniakaal {name} heerst over het dorp: eenzame overwinning.",
    repWolvesTarget: "🐺 Weerwolvenroedel → {name}",
    repNoWolvesTarget: "🐺 Weerwolvenroedel → geen slachtoffer",
    repManiacTarget: "🔪 Maniakaal → {name} (onaanwendbare aanval)",
    repSeerCheck: "🔮 {role} inspecteert {name} → {result}",
    repProtect: "🛡️ {role} beschermt {name}",
    repVillageShield: "🛡️ Ultieme Schild: hele dorp beschermd",
    repWitchLife: "⚗️ Levensdrankje gebruikt op {name}",
    repWitchPoison: "☠️ Vergif gebruikt op {name}",
    repSilence: "🤐 Zwarte Wolf zwijgt {name}",
    repSilenceSelf: "🤐 Zwarte Wolf zwijgt zichzelf ({name})",
    repInfect: "🩸 Zwarte Wolf infecteert {name}",
    repThief: "🎭 Dief ({thief}) steelt {name}'s rol → {role}; {name} wordt Dorpeling",
    repFaces: "🎭 3 gezichten gebruikt “{power}” op {name}",
    repDied: "💀 {name} ({role}) — {cause}",
    repSavedBy: "✨ {name} gered door {role}",
    repMuted: "🤐 {name} kan vandaag niet debatteren",
    repNoDeaths: "Er viel vannacht geen dode.",
    repFacePower_protect: "Bescherming",
    repFacePower_life: "Levensdrankje",
    repFacePower_poison: "Vergif",
    repFacePower_inspect: "Inspectie",
    cause_MANIAC: "vermoord door de Maniakaal",
    cause_SUICIDE_REVEAL: "Zelfmoord / rol onthuld",
    logSuicideReveal: "{name} onthulde identiteit: onmiddellijke zelfmoord.",
    cause_THREE_FACES_POISON: "vergiftigd door 3 gezichten",
    cause_WOLVES: "verslonden door de wolven",
    cause_WITCH_POISON: "vergiftigd door de Heks",
    cause_WHITE_WOLF_KILL: "gedood door de Witte Wolf",
    cause_HUNTER_SHOT: "neergeschoten door de Jager",
    cause_HEARTBREAK: "gestorven van verdriet",
    cause_VILLAGE_VOTE: "geëxecuteerd door het dorp",
    cause_JAILER_EXECUTION: "geëxecuteerd door de Cipier",
    cause_SPY_DETECTED: "betrapt door de roedel",
    cause_TALKATIVE_WOLF: "verraden door zijn stilte",
    cause_GENERAL_STRIKE: "neergeschoten door de Generaal",
    cause_GENERAL_FAILED: "geëlimineerd door de Spelleider (Generaal miste)",
    puppetSaved: "{name} werd aangevallen, maar hun pop ving de klap op! Ze overleven, maar mogen vandaag niet meedoen aan het debat.",
    repPuppetSaved: "🎭 {name} (Poppenspeler) ving de aanval op met een pop en is gemute.",
  },
  de: {
    logVoteTally: "Tag {d} — Abstimmung: [{tally}] → Eliminiert: {names}",
    lovers: "{a} und {b} sind jetzt ein Liebespaar.",
    logCupid: "Amor verbindet {a} und {b}.",
    mimeCopy: "Du kopierst die Rolle: {role}.",
    wildModel: "Dein Vorbild ist {name}.",
    jailExecuted: "{name} wird in der Zelle hingerichtet.",
    jailLocked: "{name} verbringt die Nacht eingesperrt, sicher vor den Zähnen.",
    seerSees: "{name} ist: {role}.",
    shieldUltimate: "Der Ultimative Schild umhüllt das ganze Dorf — der Beschützer verliert seine Kräfte.",
    logShieldUltimate: "Nacht {n}: Ultimativer Schild aktiviert durch {name}.",
    protectedTonight: "{name} ist heute Nacht beschützt.",
    spyCaught: "Das Rudel hat dich entdeckt... du wirst den Morgen nicht erleben.",
    spyHint: "Du erhaschst einen Blick auf eine Silhouette: Anfangsbuchstabe „{letter}“.",
    spyNothing: "Du siehst nichts in der Dunkelheit.",
    eyesClosed: "Du hältst die Augen geschlossen.",
    packDisagree: "Uneinigkeit im Rudel: Die Wölfe schlafen weiter, die Matriarchin entscheidet.",
    packChose: "Das Rudel hat {name} gewählt.",
    matriarchImpose: "Die Matriarchin bestimmt {name}.",
    logMatriarch: "Die Matriarchin entscheidet: {name}.",
    logSoloKill: "{role} verschlingt {name} (einsamer Wolf).",
    talkativeWord: "Geheimwort für den Geschwätzigen Wolf: „{word}“. Er muss es in der Debatte sagen.",
    infectBlocked: "Die Infektion schlägt fehl: Das Ziel ist geschützt.",
    logInfectBlocked: "Infektion blockiert durch den Beschützer — Kraft behalten.",
    infectJoin: "{name} tritt dem Rudel bei und behält seine Kraft.",
    logInfect: "Der Schwarze Wolf infiziert {name}.",
    silenceNote: "{name} darf morgen früh nicht mitreden.",
    logSilence: "Der Schwarze Wolf bringt {name} zum Schweigen.",
    packAsPlanned: "Das Rudel frisst wie geplant.",
    whiteTarget: "{name} wird vom Weißen Wolf gefressen.",
    witchSaved: "Das Opfer der Wölfe wurde gerettet.",
    poisoned: "{name} ist vergiftet.",
    fluteCharm: "Die Melodie bezaubert zwei neue Seelen.",
    ravenVotes: "{name} beginnt die Abstimmung mit 2 Stimmen.",
    tavernDrink: "{name} hat getrunken: Morgen kann er nicht abstimmen, ist aber unantastbar.",
    bearGrowl: "🐻 Der Bär knurrt.",
    bearCalm: "Alles ist ruhig.",
    generalWolf: "{name} war ein Wolf: Erschossen. {actor} wird der neue Hauptmann.",
    logGeneralWolf: "Der General erschießt {name} und wird Hauptmann.",
    generalFail: "{name} war kein Wolf: Der General wird vom Spielleiter eliminiert.",
    logGeneralFail: "Der Schuss des Generals verfehlt {name}.",
    generalIdle: "Der General greift heute Nacht nicht ein.",
    survivedAttack: "{name} hat den Angriff überlebt... für dieses Mal.",
    deathLine: "{name} ist tot — {cause}.",
    logDeath: "{name} ({role}) — {cause}.",
    elderFall: "Der Älteste fiel durch die Hand des Dorfes: Alle Dorfbewohner verlieren ihre Kräfte.",
    wildAwaken: "{name} spürt, wie die Bestie in ihm erwacht...",
    redRidingHood: "Rotkäppchen blieb unter dem Schutz des Jägers: Der Angriff schlägt fehl.",
    villageShieldSaved: "🛡️ Der Ultimative Schild hat heute Nacht das ganze Dorf beschützt.",
    saviorFoiled: "Der Beschützer hat den Angriff der Wölfe vereitelt.",
    jailerSafe: "Der Gefangene des Kerkermeisters war außer Reichweite.",
    bearNear: "🐻 Der Bär knurrt: Ein Wolf ist ganz in der Nähe!",
    mutedToday: "{name} ist stummgeschaltet: Er kann heute nicht debattieren.",
    nobodyDied: "Seltsamerweise ist heute Nacht niemand gestorben.",
    newCaptain: "{name} wird der neue Hauptmann.",
    day1NoVote: "Tag 1: Das Dorf weigerte sich abzustimmen.",
    logTalkativeExecuted: "Tag {d} — Geschwätziger Wolf hingerichtet (Wort nicht gesagt); Abstimmung abgesagt.",
    nightHeader: "— Nacht {n} —",
    killerFallback: "Nacht {n}: Kein Standardwolf — der Mord fällt an {role}.",
    idiotSurvives: "{name} ist der Dorfdepp: Er überlebt, verliert aber sein Stimmrecht.",
    untouchableToday: "{name} war heute unantastbar.",
    winAngel: "{name} — der Engel gewinnt: Das Dorf hat ihn am ersten Tag hingerichtet.",
    winNobody: "Niemand überlebt. Das Dorf ist ausgelöscht.",
    winLovers: "Die Liebenden gewinnen: {a} & {b}.",
    winWhiteWolf: "Der Weiße Wolf {name} bleibt allein: Einsamer Sieg.",
    winPiper: "Der Flötenspieler {name} hat das ganze Dorf bezaubert.",
    winVillage: "Das Dorf triumphiert: Es streift kein Wolf mehr umher.",
    winWolves: "Die Werwölfe haben das Dorf verschlungen.",
    thiefSteal: "Du stiehlst die Rolle von {name}: {role}. {name} wird ein einfacher Dorfbewohner.",
    logThiefSteal: "Der Dieb stiehlt die Rolle von {name} ({role}).",
    facesProtectMsg: "3 Gesichter beschützt {name} heute Nacht.",
    facesInspectMsg: "3 Gesichter entdeckt: {name} ist {role}.",
    facesLifeMsg: "3 Gesichter benutzt den Lebenstrank: Das Opfer ist gerettet.",
    facesPoisonMsg: "3 Gesichter vergiftet {name}.",
    logFaces: "3 Gesichter benutzt das Gesicht „{power}“ bei {name}.",
    maniacTargetMsg: "Der Verrückte schlägt {name} — kein Schutz kann ihn aufhalten.",
    logManiac: "Der Verrückte ermordet {name}.",
    winManiac: "Der Verrückte {name} herrscht über das Dorf: Einsamer Sieg.",
    repWolvesTarget: "🐺 Werwolfrudel → {name}",
    repNoWolvesTarget: "🐺 Werwolfrudel → kein Opfer",
    repManiacTarget: "🔪 Verrückter → {name} (unaufhaltsamer Angriff)",
    repSeerCheck: "🔮 {role} überprüft {name} → {result}",
    repProtect: "🛡️ {role} beschützt {name}",
    repVillageShield: "🛡️ Ultimativer Schild: Ganzes Dorf geschützt",
    repWitchLife: "⚗️ Lebenstrank benutzt bei {name}",
    repWitchPoison: "☠️ Gifttrank benutzt bei {name}",
    repSilence: "🤐 Schwarzer Wolf bringt {name} zum Schweigen",
    repSilenceSelf: "🤐 Schwarzer Wolf schweigt selbst ({name})",
    repInfect: "🩸 Schwarzer Wolf infiziert {name}",
    repThief: "🎭 Dieb ({thief}) stiehlt die Rolle von {name} → {role}; {name} wird Dorfbewohner",
    repFaces: "🎭 3 Gesichter benutzt „{power}“ bei {name}",
    repDied: "💀 {name} ({role}) — {cause}",
    repSavedBy: "✨ {name} gerettet durch {role}",
    repMuted: "🤐 {name} darf heute nicht debattieren",
    repNoDeaths: "Niemand starb heute Nacht.",
    repFacePower_protect: "Schutz",
    repFacePower_life: "Lebenstrank",
    repFacePower_poison: "Gifttrank",
    repFacePower_inspect: "Inspektion",
    cause_MANIAC: "vom Verrückten ermordet",
    cause_SUICIDE_REVEAL: "Selbstmord / Rolle enthüllt",
    logSuicideReveal: "{name} enthüllte Identität: sofortiger Selbstmord.",
    cause_THREE_FACES_POISON: "vergiftet von 3 Gesichtern",
    cause_WOLVES: "von den Wölfen gefressen",
    cause_WITCH_POISON: "von der Hexe vergiftet",
    cause_WHITE_WOLF_KILL: "vom Weißen Wolf getötet",
    cause_HUNTER_SHOT: "vom Jäger erschossen",
    cause_HEARTBREAK: "an gebrochenem Herzen gestorben",
    cause_VILLAGE_VOTE: "vom Dorf hingerichtet",
    cause_JAILER_EXECUTION: "vom Kerkermeister hingerichtet",
    cause_SPY_DETECTED: "vom Rudel entdeckt",
    cause_TALKATIVE_WOLF: "durch sein Schweigen verraten",
    cause_GENERAL_STRIKE: "vom General erschossen",
    cause_GENERAL_FAILED: "vom Spielleiter eliminiert (General verfehlte)",
    puppetSaved: "{name} wurde angegriffen, aber seine Puppe hat den Schlag abgefangen! Er überlebt, ist aber für die heutige Debatte stummgeschaltet.",
    repPuppetSaved: "🎭 {name} (Puppenspieler) hat den Angriff mit seiner Puppe abgefangen und ist stummgeschaltet.",
  }
};

const ROLE_NAMES: Partial<Record<Lang, Record<string, { name?: string }>>> = {
  fr: frDict.roles,
  en: enDict.roles,
  ar: arDict.roles,
  es: esDict.roles,
  pt: ptDict.roles,
  ru: ruDict.roles,
  zh: zhDict.roles,
  nl: nlDict.roles,
  de: deDict.roles,
};

function localRoleName(lang: Lang, id: string): string {
  return ROLE_NAMES[lang]?.[id]?.name ?? ROLE_BY_ID[id]?.name ?? id;
}

/** Traduit tous les jetons de narration contenus dans un texte.
 *  Analyse manuelle (accolades équilibrées) afin de supporter les jetons imbriqués. */
export function resolveNarration(text: string, lang: Lang): string {
  if (!text || !text.includes(OPEN)) return text;
  let out = "";
  let i = 0;
  while (i < text.length) {
    const start = text.indexOf(OPEN, i);
    if (start < 0) {
      out += text.slice(i);
      break;
    }
    out += text.slice(i, start);
    const close = text.indexOf(CLOSE, start);
    if (close < 0) {
      out += text.slice(start);
      break;
    }
    const key = text.slice(start + 1, close);
    // Lecture du bloc JSON avec accolades équilibrées (chaînes ignorées).
    let j = close + 1;
    let depth = 0;
    let inStr = false;
    let esc = false;
    for (; j < text.length; j++) {
      const c = text[j];
      if (inStr) {
        if (esc) esc = false;
        else if (c === "\\") esc = true;
        else if (c === '"') inStr = false;
        continue;
      }
      if (c === '"') inStr = true;
      else if (c === "{") depth++;
      else if (c === "}") {
        depth--;
        if (depth === 0) {
          j++;
          break;
        }
      }
    }
    const raw = text.slice(close + 1, j);
    let vars: Record<string, string | number> = {};
    try {
      vars = JSON.parse(raw) as Record<string, string | number>;
    } catch {
      vars = {};
    }
    if (key === "@role") {
      out += localRoleName(lang, String(vars.id ?? ""));
    } else {
      const tpl = NARRATION[lang]?.[key] ?? NARRATION.fr[key] ?? "";
      out += tpl.replace(/\{(\w+)\}/g, (m, v: string) =>
        v in vars ? resolveNarration(String(vars[v]), lang) : m,
      );
    }
    i = j;
  }
  return out;
}
